const Database = [
  {
      key:1,
      title: 'Standard Single Room',
      description: 'Standard Single Rooms are designed in open -concept living area and have many facilities.',
      bed: 1,
      capacity: 1,
      bedType: 'Single',
      price: 119, 
      amount:1,
   
  },
  {
      key:2,
      title: 'Couple Power Room',
      description: 'Superior Double Rooms are perfectly equipped for traveling couples or friends.',
        bed: 1,
      capacity: 2,
      bedType: 'Double',
      price: 149,
      amount:1,
  },
  {
      key:3,
      title: 'Family Capacity Room',
      description: ' Have lots of in-room facilities and are designed in open-concept living area.',
      bed: 2,
      capacity: 4,
      bedType: 'Family',
      price: 199,
      amount:1,
  },
  {
      key:4,
      title: 'Friends Suit',
      description: ' Have lots of in-room facilities and are designed in open-concept living area with big open wide room for 6 person',
      bed: 3,
      capacity: 6,
      bedType: 'Friends',
      price: 299,
      amount:1,
  },
  {
      key:5,
      title: 'VIP Suits',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium a ',
      bed: 2,
      capacity: 2,
      bedType: 'VIP',
      price: 699,
      amount:1,
  },
  {
      key:6,
      title: 'Sleeping Suits',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium  ',
      bed: 1,
      capacity: 1,
      bedType: 'Sleeping One Night',
      price: 150,
      amount:1,
  },
  {
      key:7,
      title: 'Sleeping Suits',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium  ',
      bed: 1,
      capacity: 1,
      bedType: 'Sleeping One Night',
      price: 150,
      amount:1,
  },
  {
      key:8,
      title: 'Sleeping Suits',
      description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium  ',
      bed: 1,
      capacity: 1,
      bedType: 'Sleeping One Night',
      price: 150,
      amount:1,
  }
]

export default Database;
